---
version: '3'
services:
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=a-sekrit-you-should-change
      - POSTGRES_DB=a-sekrit-you-should-change

  api:
    image: docker.zyxl.zyx/vcb:api
    depends_on: [postgres, redis]
    entrypoint: ''
    environment:
      - VCB_DATABASE_URL=postgres://postgres:a-sekrit-you-should-change@postgres/vcb
      - VCB_REDIS_URL=redis://redis
      - VCB_FS_ROOT=/data
      - VCB_LISTEN=0.0.0.0:3000
    command:
      - /bin/sh
      - -c
      - |
        cardboard migrate && cardboard api
    volumes:
      - $PWD/run/data:/data
      - $PWD/run/cache:/cache

  ux:
    image: docker.zyxl.zyx/vcb:ux
    depends_on: [api]
    environment:
      - VCB_BACKEND=http://api:3000
      - PORT=3001
    ports:
      - '80:3001'
