# vim:ft=dockerfile
FROM ubuntu:24.04
RUN apt-get update \
 && apt-get install -y libpq5 curl ca-certificates jq \
 && rm -rf /var/lib/apt/lists/*

RUN curl -sLo /usr/bin/s3 https://github.com/jhunt/s3/releases/download/v0.3.1/s3-linux-amd64 \
 && chmod 0755 /usr/bin/s3

COPY ingest /usr/bin/ingest
