FROM vault-of-cardboard-base:dev AS build
FROM ubuntu:18.04
RUN apt-get update \
 && apt-get install -y libpq5 \
 && rm -rf /var/lib/apt/lists/*
COPY --from=build /bins/vaultd /vaultd
ENTRYPOINT ["/vaultd"]
# vim:ft=Dockerfile
