---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: vcb
  generateName: rescry-
  name: rescry
spec:
  template:
    metadata:
      labels:
        k8s.vaultofcardboard.com/job: rescryer
    spec:
      restartPolicy: OnFailure

      volumes:
        - name: vault
          hostPath:
            path: /srv/vcb

      imagePullSecrets:
        - name: docker-zyxl-key

      containers:
        - name: rescryer
          image: docker.zyxl.xyz/vcb/cardboard:latest
          imagePullPolicy: Always
          env:
            - name:  CACHE
              value: /cache
            - name:  DATA
              value: /data
          command:
            - /cardboard
            - rescry
            - -r
            - /cache/dat
            - -c
            - /data/cards.json
            - -p
            - /data/prices.json
            - -l
            - /data/lookup.json

          volumeMounts:
            - name: vault
              subPath: cache
              mountPath: /cache
            - name: vault
              subPath: data
              mountPath: /data
