#!/usr/bin/perl
use strict;
use warnings;
use List::Util qw/sum/;
use POSIX qw/ceil/;

chomp(my $run = <>);
print "VAULT OF CARDBOARD\n";
print "PARSER BENCHMARK\n\n";
print "run $run...\n\n";

printf "%8s  %12s  %12s  %12s  %12s  %12s\n", ('=' x 6), ('=' x 10), ('=' x 10), ('=' x 10), ('=' x 10), ('=' x 10);
printf "%8s  %12s  %12s  %12s  %12s  %12s\n", "RUN", "CARDS", "MS", "C/ms", "ms/C", "C<200ms";
printf "%8s  %12s  %12s  %12s  %12s  %12s\n", ('=' x 6), ('=' x 10), ('=' x 10), ('=' x 10), ('=' x 10), ('=' x 10);
my (@CPM, @MPC);
while (<>) {
	chomp;
	my ($run, $cards, $ms) = split /:/;
	my $cards_per_ms = $cards * 1.0 / $ms;
	my $ms_per_card  = $ms * 1.0 / $cards;

	push @CPM, $cards_per_ms;
	push @MPC, $ms_per_card;

	printf "%8s  %12d  %12d  %12.2lf  %12.2le  %12d\n",
		$run, $cards, $ms, $cards_per_ms, $ms_per_card, int($cards_per_ms * 200);
}

sub median {
	sum((sort { $a <=> $b } @_)[ int($#_/2), ceil($#_/2) ])/2;
}

sub mean {
	sum(@_)/@_;
}


printf "%36s  %12s  %12s  %12s\n", ('-' x 34), ('-' x 10), ('-' x 10), ('-' x 10);
printf "%36s  %12.2lf  %12.2le  %12.2lf k\n", "MEAN", mean(@CPM), mean(@MPC), int(mean(@CPM) * 200) / 1000;
printf "%36s  %12.2lf  %12.2le  %12.2lf k\n", "MEDIAN", median(@CPM), median(@MPC), int(median(@CPM) * 200) / 1000;
print "\nrun $run...\n\n";
print "VAULT OF CARDBOARD\n";
print "PARSER BENCHMARK\n";
